use text_splitter::{ChunkConfig, MarkdownSplitter};
use tiktoken_rs::cl100k_base;
use crate::types::{SectionMetadata, ChunkMetadata};
use cuid2::create_id;

pub struct Chunker {
    splitter: MarkdownSplitter<tiktoken_rs::CoreBPE>,
    tokenizer: tiktoken_rs::CoreBPE,
}

impl Chunker {
    /// Initialize a new Chunker with Tiktoken (cl100k_base) sizer.
    pub fn new() -> Self {
        let tokenizer = cl100k_base().unwrap();
        let splitter = MarkdownSplitter::new(
            ChunkConfig::new(800)
                .with_overlap(80)
                .expect("Valid overlap")
                .with_sizer(cl100k_base().unwrap())
        );
        Self { splitter, tokenizer }
    }

    /// Split a section into multiple chunks with contextual enrichment.
    pub fn chunk_section(&self, doc_title: &str, section: &SectionMetadata) -> Vec<ChunkMetadata> {
        let fragments = self.splitter.chunks(&section.text_content);
        
        fragments.enumerate().map(|(idx, fragment)| {
            // 1. Contextual enrichment for better retrieval accuracy
            let enriched_text = format!(
                "Document: {}\nSection: {}\n\n{}",
                doc_title,
                section.heading_text,
                fragment
            );

            // 2. Token count using the same tokenizer
            let tokens = self.tokenizer.encode_with_special_tokens(&enriched_text);
            
            ChunkMetadata {
                id: create_id(),
                index: idx as i32,
                heading_path: Some(section.heading_text.clone()),
                heading_id: section.heading_id.clone(),
                chunk_text: enriched_text,
                embedding: vec![], // To be generated by EmbedClient later
                token_count: tokens.len() as i32,
                has_code: fragment.contains("```"),
            }
        }).collect()
    }
}
